package com.owlafrica.servicebuilder.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.owlafrica.servicebuilder.model.Dep;
import com.owlafrica.servicebuilder.service.DepLocalServiceUtil;

/**
 * The extended model base implementation for the Dep service. Represents a row in the &quot;Dep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepImpl
 * @see com.owlafrica.servicebuilder.model.Dep
 * @generated
 */
public abstract class DepBaseImpl extends DepModelImpl implements Dep {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dep model instance should use the {@link Dep} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DepLocalServiceUtil.addDep(this);
        } else {
            DepLocalServiceUtil.updateDep(this);
        }
    }
}
