package com.owlafrica.servicebuilder.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.owlafrica.servicebuilder.model.LiferayAspenReference;
import com.owlafrica.servicebuilder.model.LiferayAspenReferenceModel;
import com.owlafrica.servicebuilder.model.LiferayAspenReferenceSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LiferayAspenReference service. Represents a row in the &quot;liferay_aspen_reference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.owlafrica.servicebuilder.model.LiferayAspenReferenceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LiferayAspenReferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LiferayAspenReferenceImpl
 * @see com.owlafrica.servicebuilder.model.LiferayAspenReference
 * @see com.owlafrica.servicebuilder.model.LiferayAspenReferenceModel
 * @generated
 */
@JSON(strict = true)
public class LiferayAspenReferenceModelImpl extends BaseModelImpl<LiferayAspenReference>
    implements LiferayAspenReferenceModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a liferay aspen reference model instance should use the {@link com.owlafrica.servicebuilder.model.LiferayAspenReference} interface instead.
     */
    public static final String TABLE_NAME = "liferay_aspen_reference";
    public static final Object[][] TABLE_COLUMNS = {
            { "lar_id", Types.BIGINT },
            { "lf_user_id", Types.BIGINT },
            { "aspen_employee_code", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table liferay_aspen_reference (lar_id LONG not null primary key,lf_user_id LONG,aspen_employee_code VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table liferay_aspen_reference";
    public static final String ORDER_BY_JPQL = " ORDER BY liferayAspenReference.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY liferay_aspen_reference.lar_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.owlafrica.servicebuilder.model.LiferayAspenReference"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.owlafrica.servicebuilder.model.LiferayAspenReference"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.owlafrica.servicebuilder.model.LiferayAspenReference"));
    private static ClassLoader _classLoader = LiferayAspenReference.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LiferayAspenReference.class
        };
    private long _id;
    private long _liferayUserId;
    private String _liferayUserUuid;
    private String _aspenEmployeeCode;
    private LiferayAspenReference _escapedModel;

    public LiferayAspenReferenceModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static LiferayAspenReference toModel(
        LiferayAspenReferenceSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        LiferayAspenReference model = new LiferayAspenReferenceImpl();

        model.setId(soapModel.getId());
        model.setLiferayUserId(soapModel.getLiferayUserId());
        model.setAspenEmployeeCode(soapModel.getAspenEmployeeCode());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<LiferayAspenReference> toModels(
        LiferayAspenReferenceSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<LiferayAspenReference> models = new ArrayList<LiferayAspenReference>(soapModels.length);

        for (LiferayAspenReferenceSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LiferayAspenReference.class;
    }

    @Override
    public String getModelClassName() {
        return LiferayAspenReference.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("liferayUserId", getLiferayUserId());
        attributes.put("aspenEmployeeCode", getAspenEmployeeCode());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Long liferayUserId = (Long) attributes.get("liferayUserId");

        if (liferayUserId != null) {
            setLiferayUserId(liferayUserId);
        }

        String aspenEmployeeCode = (String) attributes.get("aspenEmployeeCode");

        if (aspenEmployeeCode != null) {
            setAspenEmployeeCode(aspenEmployeeCode);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public long getLiferayUserId() {
        return _liferayUserId;
    }

    @Override
    public void setLiferayUserId(long liferayUserId) {
        _liferayUserId = liferayUserId;
    }

    @Override
    public String getLiferayUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getLiferayUserId(), "uuid",
            _liferayUserUuid);
    }

    @Override
    public void setLiferayUserUuid(String liferayUserUuid) {
        _liferayUserUuid = liferayUserUuid;
    }

    @JSON
    @Override
    public String getAspenEmployeeCode() {
        if (_aspenEmployeeCode == null) {
            return StringPool.BLANK;
        } else {
            return _aspenEmployeeCode;
        }
    }

    @Override
    public void setAspenEmployeeCode(String aspenEmployeeCode) {
        _aspenEmployeeCode = aspenEmployeeCode;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LiferayAspenReference.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LiferayAspenReference toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LiferayAspenReference) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LiferayAspenReferenceImpl liferayAspenReferenceImpl = new LiferayAspenReferenceImpl();

        liferayAspenReferenceImpl.setId(getId());
        liferayAspenReferenceImpl.setLiferayUserId(getLiferayUserId());
        liferayAspenReferenceImpl.setAspenEmployeeCode(getAspenEmployeeCode());

        liferayAspenReferenceImpl.resetOriginalValues();

        return liferayAspenReferenceImpl;
    }

    @Override
    public int compareTo(LiferayAspenReference liferayAspenReference) {
        long primaryKey = liferayAspenReference.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LiferayAspenReference)) {
            return false;
        }

        LiferayAspenReference liferayAspenReference = (LiferayAspenReference) obj;

        long primaryKey = liferayAspenReference.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<LiferayAspenReference> toCacheModel() {
        LiferayAspenReferenceCacheModel liferayAspenReferenceCacheModel = new LiferayAspenReferenceCacheModel();

        liferayAspenReferenceCacheModel.id = getId();

        liferayAspenReferenceCacheModel.liferayUserId = getLiferayUserId();

        liferayAspenReferenceCacheModel.aspenEmployeeCode = getAspenEmployeeCode();

        String aspenEmployeeCode = liferayAspenReferenceCacheModel.aspenEmployeeCode;

        if ((aspenEmployeeCode != null) && (aspenEmployeeCode.length() == 0)) {
            liferayAspenReferenceCacheModel.aspenEmployeeCode = null;
        }

        return liferayAspenReferenceCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", liferayUserId=");
        sb.append(getLiferayUserId());
        sb.append(", aspenEmployeeCode=");
        sb.append(getAspenEmployeeCode());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("com.owlafrica.servicebuilder.model.LiferayAspenReference");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>liferayUserId</column-name><column-value><![CDATA[");
        sb.append(getLiferayUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>aspenEmployeeCode</column-name><column-value><![CDATA[");
        sb.append(getAspenEmployeeCode());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
