package com.owlafrica.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.owlafrica.servicebuilder.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.owlafrica.servicebuilder.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see com.owlafrica.servicebuilder.model.impl.EmployeeImpl
 * @see com.owlafrica.servicebuilder.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this employee.
     *
     * @return the ID of this employee
     */
    public long getId();

    /**
     * Sets the ID of this employee.
     *
     * @param id the ID of this employee
     */
    public void setId(long id);

    /**
     * Returns the birthday of this employee.
     *
     * @return the birthday of this employee
     */
    public Date getBirthday();

    /**
     * Sets the birthday of this employee.
     *
     * @param birthday the birthday of this employee
     */
    public void setBirthday(Date birthday);

    /**
     * Returns the e mail of this employee.
     *
     * @return the e mail of this employee
     */
    @AutoEscape
    public String getEMail();

    /**
     * Sets the e mail of this employee.
     *
     * @param eMail the e mail of this employee
     */
    public void setEMail(String eMail);

    /**
     * Returns the first name of this employee.
     *
     * @return the first name of this employee
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this employee.
     *
     * @param firstName the first name of this employee
     */
    public void setFirstName(String firstName);

    /**
     * Returns the second name of this employee.
     *
     * @return the second name of this employee
     */
    @AutoEscape
    public String getSecondName();

    /**
     * Sets the second name of this employee.
     *
     * @param secondName the second name of this employee
     */
    public void setSecondName(String secondName);

    /**
     * Returns the grade of this employee.
     *
     * @return the grade of this employee
     */
    public int getGrade();

    /**
     * Sets the grade of this employee.
     *
     * @param grade the grade of this employee
     */
    public void setGrade(int grade);

    /**
     * Returns the dep i d of this employee.
     *
     * @return the dep i d of this employee
     */
    public long getDepID();

    /**
     * Sets the dep i d of this employee.
     *
     * @param depID the dep i d of this employee
     */
    public void setDepID(long depID);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.owlafrica.servicebuilder.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.owlafrica.servicebuilder.model.Employee> toCacheModel();

    @Override
    public com.owlafrica.servicebuilder.model.Employee toEscapedModel();

    @Override
    public com.owlafrica.servicebuilder.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
