package com.owlafrica.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LiferayAspenReference service. Represents a row in the &quot;liferay_aspen_reference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.owlafrica.servicebuilder.model.impl.LiferayAspenReferenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.owlafrica.servicebuilder.model.impl.LiferayAspenReferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LiferayAspenReference
 * @see com.owlafrica.servicebuilder.model.impl.LiferayAspenReferenceImpl
 * @see com.owlafrica.servicebuilder.model.impl.LiferayAspenReferenceModelImpl
 * @generated
 */
public interface LiferayAspenReferenceModel extends BaseModel<LiferayAspenReference> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a liferay aspen reference model instance should use the {@link LiferayAspenReference} interface instead.
     */

    /**
     * Returns the primary key of this liferay aspen reference.
     *
     * @return the primary key of this liferay aspen reference
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this liferay aspen reference.
     *
     * @param primaryKey the primary key of this liferay aspen reference
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this liferay aspen reference.
     *
     * @return the ID of this liferay aspen reference
     */
    public long getId();

    /**
     * Sets the ID of this liferay aspen reference.
     *
     * @param id the ID of this liferay aspen reference
     */
    public void setId(long id);

    /**
     * Returns the liferay user ID of this liferay aspen reference.
     *
     * @return the liferay user ID of this liferay aspen reference
     */
    public long getLiferayUserId();

    /**
     * Sets the liferay user ID of this liferay aspen reference.
     *
     * @param liferayUserId the liferay user ID of this liferay aspen reference
     */
    public void setLiferayUserId(long liferayUserId);

    /**
     * Returns the liferay user uuid of this liferay aspen reference.
     *
     * @return the liferay user uuid of this liferay aspen reference
     * @throws SystemException if a system exception occurred
     */
    public String getLiferayUserUuid() throws SystemException;

    /**
     * Sets the liferay user uuid of this liferay aspen reference.
     *
     * @param liferayUserUuid the liferay user uuid of this liferay aspen reference
     */
    public void setLiferayUserUuid(String liferayUserUuid);

    /**
     * Returns the aspen employee code of this liferay aspen reference.
     *
     * @return the aspen employee code of this liferay aspen reference
     */
    @AutoEscape
    public String getAspenEmployeeCode();

    /**
     * Sets the aspen employee code of this liferay aspen reference.
     *
     * @param aspenEmployeeCode the aspen employee code of this liferay aspen reference
     */
    public void setAspenEmployeeCode(String aspenEmployeeCode);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.owlafrica.servicebuilder.model.LiferayAspenReference liferayAspenReference);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.owlafrica.servicebuilder.model.LiferayAspenReference> toCacheModel();

    @Override
    public com.owlafrica.servicebuilder.model.LiferayAspenReference toEscapedModel();

    @Override
    public com.owlafrica.servicebuilder.model.LiferayAspenReference toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
